# Generated by Django 3.2.4 on 2021-06-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='asd', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
