# Generated by Django 3.2.4 on 2021-06-04 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('voen', models.CharField(max_length=50)),
                ('identity_number', models.PositiveIntegerField()),
                ('given_date', models.DateTimeField()),
                ('given_organization_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JuridicalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('voen', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=50)),
                ('organization_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_juridical', models.BooleanField(default=False)),
                ('is_individual', models.BooleanField(default=False)),
                ('individual_person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.individualperson')),
                ('juridical_person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.juridicalperson')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='contracts.person')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='contracts.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
