# Generated by Django 3.2.4 on 2021-06-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210605_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_individual',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_juridical',
        ),
    ]
