# Generated by Django 3.2.4 on 2021-06-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
