# Generated by Django 3.2.4 on 2021-06-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20210605_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
